from django.urls import path
from . import views

urlpatterns = [
    path('', views.main_view, name='home'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('venue/<int:venue_id>/', views.venue_detail_view, name='venue_detail'),
    path('dashboard/customer/', views.customer_dashboard_view, name='customer_dashboard'),
    path('dashboard/venue/', views.venue_dashboard_view, name='venue_dashboard'),
    path('dashboard/venue/add/', views.venue_create_view, name='venue_create'),
    path('dashboard/venue/<int:venue_id>/manage/', views.venue_manage_view, name='venue_manage'),
    path('dashboard/coach/', views.coach_dashboard_view, name='coach_dashboard'),
    path('dashboard/admin/', views.admin_dashboard_view, name='admin_dashboard'),
    path('dashboard/venue/revenue/', views.venue_revenue_view, name='venue_revenue'),
    path('venue/delete/<int:venue_id>/', views.delete_venue_view, name='delete_venue'),
    path('venue/<int:venue_id>/book/', views.create_booking, name='create_booking'),
    path('customer/payment/<int:booking_id>/', views.customer_payment, name='customer_payment'),
    path('history/', views.booking_history, name='booking_history'),
    path('my-bookings/', views.my_bookings, name='my_bookings'),
    path('coach/profile/', views.manage_coach_profile, name='manage_coach_profile'),
    path('coach/profile/view/', views.coach_profile_view, name='coach_profile'),
    path('coach/profile/delete/', views.delete_coach_profile, name='delete_coach_profile'),
    path('coach/schedule/', views.coach_schedule, name='coach_schedule'),
    path('coach/schedule/delete/', views.coach_schedule_delete, name='coach_schedule_delete'),
    path('coaches/', views.coach_list_view, name='coach_list'),
    path('coach/<int:coach_id>/', views.coach_detail_public_view, name='coach_detail_public'),
    path('booking/delete/<int:booking_id>/', views.delete_booking, name='delete_booking'),
    path('coach/revenue-report/', views.coach_revenue_report, name='coach_revenue_report'),
    path('venue/<int:venue_id>/schedules/delete/', views.venue_schedule_delete, name='venue_schedule_delete'),
    path('dashboard/venue/<int:venue_id>/schedules/manage/', views.venue_manage_schedule_view, name='venue_manage_schedule'),
    path('api/schedule/<int:schedule_id>/coaches/', views.get_available_coaches, name='get_available_coaches'),
]