# Generated by Django 5.2.7 on 2025-10-22 11:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20251018_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='coach_profiles/'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='main_sport_trained',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coaches_by_sport', to='main.sportcategory'),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='rate_per_hour',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='coachprofile',
            name='service_areas',
            field=models.ManyToManyField(blank=True, related_name='coaches_serving', to='main.locationarea'),
        ),
        migrations.CreateModel(
            name='CoachVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_rates', to='main.coachprofile')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_rates', to='main.venue')),
            ],
            options={
                'unique_together': {('coach', 'venue')},
            },
        ),
    ]
