# Generated by Django 5.2.7 on 2025-10-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20251018_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='coach_photos/', verbose_name='Foto Profil'),
        ),
        migrations.AddField(
            model_name='venue',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='venue_photos/', verbose_name='Foto Utama Lapangan'),
        ),
    ]
