# Generated by Django 5.2.7 on 2025-12-20 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_booking_coach_schedule_alter_booking_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingequipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.equipment'),
        ),
    ]
