# Generated by Django 5.2.7 on 2025-12-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bookingequipment_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True, verbose_name='URL Foto Profil'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='main_image',
            field=models.URLField(blank=True, null=True, verbose_name='URL Foto Utama Lapangan'),
        ),
    ]
